### ISSUE TITLE
How do i remove (entirely) the mod ?

### ISSUE THREAD

**Issue by Moustavats** [Rist8/MiSide-Console-Unlocker#2]
i deleted every thing and redownloaded the game but i still can open the console, i would like to ask how i can get rid of that too and get the game back to normal please
![sdfsdssdf](https://github.com/user-attachments/assets/906142eb-3e00-437b-af2e-38d401ff6790)

**Comment by Rist8** [comment]
Reinstall the mod, open and close the game and you will have the lite version of the console again.
