### ISSUE TITLE
не работает разблокировка консоли 

### ISSUE THREAD

**Issue by NeuroDonu** [Rist8/MiSide-Console-Unlocker#4]
привет.
я поставил все по гайду, но есть одно маленькое НО - я использую линукс и эмулирую это все дело через portproton. все лежит в папке, консоль работает, но она неполная, хотя мод лежит (скрин)
![изображение](https://github.com/user-attachments/assets/154c1eee-b3e1-4467-bf00-d8c7f82a82b3)
но при этом: 
![изображение](https://github.com/user-attachments/assets/7c4cbb64-9bcd-4d5d-a11e-83f0df82e2cc)
настройки протона такие:
![изображение](https://github.com/user-attachments/assets/4e33a318-9352-4f89-9fad-1e916bb541f3)

**Comment by Rist8** [comment]
Does BepInEx work at all on your setup?

Работает ли BepInEx в принципе на твоей системе?

**Comment by NeuroDonu** [comment]
> Does BepInEx work at all on your setup?
> 
> Работает ли BepInEx в принципе на твоей системе?

да, работает. консоль доступна

**Comment by Rist8** [comment]
А какие логи в консоли BepInEx?

**Comment by NeuroDonu** [comment]
а ее и нет!

**Comment by Rist8** [comment]
> > Does BepInEx work at all on your setup?
> > Работает ли BepInEx в принципе на твоей системе?
> 
> да, работает. консоль доступна

?

**Comment by NeuroDonu** [comment]
счас, заново скачаю, запишу видео и скину

**Comment by NeuroDonu** [comment]
не смог загрузить видос на гит, он 18мб :/ 
https://drive.google.com/file/d/1nbQRh0HEXvl09_dCMMEKrjfssQKVe_rx/view?usp=sharing

**Comment by Rist8** [comment]
Я не вижу чтобы открывалась консоль BepInEx, которая должна открывается перед игрой и быть активной вместе с игрой до закрытия

**Comment by NeuroDonu** [comment]
ага, и я хз почему. на винде все ок работает. на лине - нет. но на винде у меня жалкие 11 фпс (она лишь интеграшку видет. что странно), а на эмуле все 60

**Comment by Rist8** [comment]
Ну если нет консоли BepInEx значит он не работает на таком сетапе, а это значит что не будет работать и мод

**Comment by asvdvl** [comment]
@NeuroDonu 
Есть инструкция специально под wine/proton:
There is an instruction specifically for wine/proton:
https://docs.bepinex.dev/articles/advanced/proton_wine.html

**Comment by NeuroDonu** [comment]
Оо, спасибо!
