### ISSUE TITLE
About uninstalling

### ISSUE THREAD

**Issue by djdjfjfkeocj** [Rist8/MiSide-Console-Unlocker#8]
Recent MISIDE update. So I uninstalled the game on Steam based on my experience with other game mods and deleted the root directory of the game to prevent any residual mods (I only installed this mod), and then re-downloaded it, but I found that the re-downloaded game still evokes the console. Does this mod feature enable the existing console in the game or is it a console? (I was upset when I redownloaded it and found that I could also call the console, as I wasn't sure if my mod wasn't uninstalled clean.) I'd like to confirm)

If not, what should I do? 

The above is machine translation

**Comment by Rist8** [comment]
Developers of the game must have unlocked the in-game console in the latest update, so it is available by default.

**Comment by Rist8** [comment]
So now the entire sense of this mod is in keys binding
